const state={jobs:[],meta:{}};
const $=id=>document.getElementById(id);
async function load(){try{const r=await fetch('data/jobs.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('data unavailable');const payload=await r.json();state.jobs=Array.isArray(payload)?payload:(payload.jobs||[]);state.meta=payload.meta||{};renderFilters();render()}catch(e){$('jobs').innerHTML='<div class="empty"><h2>Dashboard data unavailable</h2><p>Run the private Job Search Agent workflow and refresh this page.</p></div>'}}
function renderFilters(){const uniq=(key)=>[...new Set(state.jobs.map(j=>j[key]).filter(Boolean))].sort();for(const [id,key] of [['source','source'],['location','location']]){const el=$(id);uniq(key).forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;el.appendChild(o)})}}
function render(){const q=$('search').value.toLowerCase().trim(),source=$('source').value,location=$('location').value,min=Number($('score').value),sort=$('sort').value;let jobs=state.jobs.filter(j=>{const hay=[j.title,j.company,j.location,j.description,j.skills,j.source].filter(Boolean).join(' ').toLowerCase();return(!q||hay.includes(q))&&(!source||j.source===source)&&(!location||j.location===location)&&(Number(j.match_score||0)>=min)});jobs.sort((a,b)=>sort==='score'?Number(b.match_score||0)-Number(a.match_score||0):sort==='company'?(a.company||'').localeCompare(b.company||''):sort==='title'?(a.title||'').localeCompare(b.title||''):String(b.posted_at||'').localeCompare(String(a.posted_at||'')));$('count').textContent=`${jobs.length} job${jobs.length===1?'':'s'}`;$('sourceSummary').textContent=[...new Set(jobs.map(j=>j.source).filter(Boolean))].join(' • ');$('jobs').innerHTML=jobs.map(card).join('');$('empty').classList.toggle('hidden',jobs.length>0);stats()}
function card(j){const skills=Array.isArray(j.skills)?j.skills:(typeof j.skills==='string'?j.skills.split(',').map(x=>x.trim()).filter(Boolean):[]);const salary=j.salary||j.salary_text;const details=[j.location,j.employment_type,j.experience,j.company_size||'Company size not available',salary].filter(Boolean).join('  •  ');return `<article class="job"><div><div class="job-top"><div><h2>${esc(j.title||'Untitled role')}</h2><div class="company">${esc(j.company||'Company not listed')}</div><div class="meta">${esc(details)}</div></div><span class="score">${Number(j.match_score||0)}% match</span></div>${skills.length?`<div class="tags">${skills.slice(0,8).map(s=>`<span class="tag">${esc(s)}</span>`).join('')}</div>`:''}${j.description?`<div class="details">${esc(strip(j.description).slice(0,240))}${strip(j.description).length>240?'…':''}</div>`:''}</div><div class="actions"><a class="button primary" href="${esc(j.original_url||j.redirect_url||'#')}" target="_blank" rel="noopener">View job ↗</a></div></article>`}
function stats(){const m=state.meta;const cards=[['Matched jobs',m.saved_matches??state.jobs.length],['80%+ matches',state.jobs.filter(j=>Number(j.match_score||0)>=80).length],['New jobs',m.new_jobs??0],['Sources',Object.keys(m.sources||{}).length||new Set(state.jobs.map(j=>j.source).filter(Boolean)).size]];$('stats').innerHTML=cards.map(c=>`<div class="stat"><div class="stat-label">${c[0]}</div><div class="stat-value">${c[1]}</div></div>`).join('');$('updated').textContent=m.last_run_utc?`Updated ${new Date(m.last_run_utc).toLocaleString()}`:'Waiting for first run'}
function strip(s){return String(s).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
['search','source','location','score','sort'].forEach(id=>$(id).addEventListener('input',render));load();
